require('proof')(4, (okay) => {
    const fs = require('fs')
    const path = require('path')
    const stack = fs.readFileSync(path.join(__dirname, 'parse.txt'), 'utf8')
    const parse = require('../parse')
    const parsed = parse(stack)
    okay(parsed.context, { a: 1 }, 'parsed context')
    okay(parsed.errors[2], '1', 'parsed nested')
    okay(parse(''), null, 'parsed nope')
    okay(parsed.errors[1].contexts[0], { a: { c: 3  } }, 'parsed error context')
})
